version: '3.6'
services:
  mysql:
    image: mysql:8.0.24
    container_name: materiaguas_mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql-8.024:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - 3306:3306

volumes:
  mysql-8.024: