version: '3.6'
services:
  db:
    image: mysql:8.0.24
    container_name: materiaguas_mysql2
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - mysql-8.024-1:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    networks:
      - materiaguas

  app:
    image: materiaguassys
    build:
      context: .
    container_name: materiaguassys
    command: ['bundle', 'exec', 'rails', 's', '-b', '0.0.0.0']
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - bundle-cache-2.3.8:/bundle
      - ".:/usr/src/app"
      - "./root_user:/root"
    depends_on:
      - db
    networks:
      - materiaguas

networks:
  materiaguas:
    driver: bridge

volumes:
  mysql-8.024-1:
  bundle-cache-2.3.8: