services:
  - type: web
    name: materiaguas
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    healthCheckPath: /
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RACK_ENV
        value: production
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: DB_HOST
        fromDatabase:
          name: materiaguas_db
          property: host
      - key: DB_USERNAME
        fromDatabase:
          name: materiaguas_db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: materiaguas_db
          property: password
      - key: DB_PORT
        fromDatabase:
          name: materiaguas_db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: materiaguas_db
          property: database
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"
      - key: RAILS_LOG_TO_STDOUT
        value: "true"

databases:
  - name: materiaguas_db
    engine: postgres
    plan: starter
