default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("DB_POOL") { 5 } %>
  reconnect: true

development:
  <<: *default
  host: <%= ENV.fetch('DB_HOST') { '127.0.0.1' } %>
  username: <%= ENV.fetch('DB_USERNAME') { 'root' } %>
  password: <%= ENV.fetch('DB_PASSWORD') { 'password' } %>
  port: <%= ENV.fetch('DB_PORT') { 3306 } %>
  database: <%= ENV.fetch("DB_NAME") { 'materiaguas_development' } %>

test:
  <<: *default
  host: <%= ENV.fetch('DB_HOST') { '127.0.0.1' } %>
  username: <%= ENV.fetch('DB_USERNAME') { 'root' } %>
  password: <%= ENV.fetch('DB_PASSWORD') { 'password' } %>
  port: <%= ENV.fetch('DB_PORT') { 3306 } %>
  database: <%= ENV.fetch("DB_NAME") { 'materiaguas_test' } %>

production:
  <<: *default
  host: <%= ENV['DB_HOST'] || 'db' %>
  username: <%= ENV['DB_USERNAME'] || 'root' %>
  password: <%= ENV['DB_PASSWORD'] %>
  port: <%= ENV['DB_PORT'] || 3306 %>
  database: <%= ENV['DB_NAME'] || 'materiaguas_production' %>
