development:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] || ENV['SECRET_TOKEN'] || 'dev_secret_key_base_123' %>

test:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] || ENV['SECRET_TOKEN'] || 'test_secret_key_base_123' %>

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] || ENV['SECRET_TOKEN'] %>